name: Publish

on: [push]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["mobx", "mobx_codegen"]

    steps:
      - uses: actions/checkout@v2

      - name: ${{ matrix.package }}
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}

      - name: Tag commit
        if: steps.publish.outputs.remoteVersion != steps.publish.outputs.localVersion
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.remoteVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_flutter_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["flutter_mobx"]

    steps:
      - uses: actions/checkout@v2

      - name: ${{ matrix.package }}
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}

      - name: Tag commit
        if: steps.publish.outputs.remoteVersion != steps.publish.outputs.localVersion
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.remoteVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
